name: API CI
#on: [push] # For normal repositories (no monorepos)
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: ./api/package-lock.json

    - name: Intall dependencies
      shell: bash
      run: npm ci

    - name: Lint with ESLint
      shell: bash
      run: npm run lint

    - name: Run unit test
      shell: bash
      run: npm run test
