name: API CI
#on: [push] # For normal repositories (no monorepos)
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 18
        cache: 'npm'

    - name: install
      shell: bash
      run: npm ci

    - name: run unit test
      shell: bash
      run: npm run test


