name: API CI
#on: [push] # For normal repositories (no monorepos)
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: ./api/package-lock.json

    - name: Intall dependencies
      shell: bash
      run: npm ci

    - name: Lint with ESLint
      shell: bash
      run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: ./api/package-lock.json

    - name: Intall dependencies
      shell: bash
      run: npm ci

    - name: Unit test
      shell: bash
      run: npm run test

  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:18

    services:
      mongo-e2e:
        image: mongo:4.4
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test123
        ports:
          - 27017:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Intall dependencies
        shell: bash
        run: npm ci
      - name: Run E2E test
        shell: bash
        run: npm run test:e2e
        env:
          MONGO_DB_NAME: demo
          MONGO_URL: mongodb://test:test123@mongo-e2e:27017?retryWrites=true&writeConcern=majority
